### ISSUE TITLE
Please fix your application to use the native API of Avahi!

### ISSUE THREAD

**Issue by juergenschubert** [olivierguerriat/hassio-addons#8]
starting version 3.2.1
Linking the homebridge config directory
Launching DBUS daemon…
Launching avahi daemon…
Launching homebridge…
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[8/9/2017, 8:43:26 AM] Loaded plugin: homebridge-homeassistant

I am running the latest Home Assistiant Code on HASSIO 0.50.2

**Comment by fonta** [comment]
This is not an issue in this package but in homebridge itself and won't be fixed.
See https://github.com/nfarina/homebridge#errors-on-startup

**Comment by olivierguerriat** [comment]
This is indeed unrelated to this package and deemed acceptable. However, [please note that this add-on is deprecated and doesn't work anymore](https://github.com/olivierguerriat/hassio-addons/tree/master/homebridge).
